### ISSUE TITLE
Spectra in HDF5 format

### ISSUE THREAD

**Issue by sheliak** [sheliak/galah_reduction#3]
Someone has to do it. I suggest a folder utils with some scripts that do things like rewrite the database in new format, produce hdf spectra etc.

**Comment by kcotar** [comment]
We have to decide on the HDF5 structure. I propose the one implemented in https://github.com/kcotar/Spectra_database_HDF5_Galah, but this one is meant for a spectral database that is resampled to a constant linearized wavelength scale. What are the requirements by the collaboration? If none, we can provide the script that handles data access.
